name: xgp

on:
  workflow_dispatch:
  schedule:
    - cron: '23 * * * *'
jobs:
  xgp:
    runs-on: windows-2022
    
    steps:
      - name: 'xgp' 
        run: |
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritysdx/ggg/main/Sign_google.py
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/chromedriver.exe
          cmd /c curl -s -O https://raw.githubusercontent.com/spiritLHL/Gecko_sign/master/requirements.txt
          cmd /c pip install -r requirements.txt
          cmd /c python Sign_google.py '0'
